Repository Clo-fi/Codeython-server, pull requests merged in 2024-04, with the labels that each got.

#6 feat.회원가입 기능 구현
  http/member/CreateMember.http
  src/main/java/clofi/codeython/CodeythonApplication.java
  src/main/java/clofi/codeython/common/controller/ExceptionControllerAdvice.java
  src/main/java/clofi/codeython/common/domain/BaseEntity.java
  src/main/java/clofi/codeython/common/domain/dto/ExceptionResult.java
  src/main/java/clofi/codeython/user/controller/MemberController.java
  src/main/java/clofi/codeython/user/domain/Member.java
  src/main/java/clofi/codeython/user/domain/request/CreateMemberRequest.java
  src/main/java/clofi/codeython/user/repository/MemberRepository.java
  src/main/java/clofi/codeython/user/service/MemberService.java
  src/test/java/clofi/codeython/user/service/MemberServiceTest.java
Labels: feat

#9 멤버 닉네임 업데이트 및 정보 조회 구현
  http/member/CreateMember.http
  src/main/java/clofi/codeython/common/controller/ExceptionControllerAdvice.java
  src/main/java/clofi/codeython/user/controller/MemberController.java
  src/main/java/clofi/codeython/user/controller/response/MemberResponse.java
  src/main/java/clofi/codeython/user/domain/Member.java
  src/main/java/clofi/codeython/user/domain/request/UpdateMemberRequest.java
  src/main/java/clofi/codeython/user/repository/MemberRepository.java
  src/main/java/clofi/codeython/user/service/MemberService.java
  src/test/java/clofi/codeython/user/service/MemberServiceTest.java
Labels: feat

#14 Feat/#11
  Dockerfile
  k8s/backend.yaml
  k8s/ingress.yaml
  k8s/kustomization.yaml
Labels: feat

#16 배포 설정 추가
  Dockerfile
  k8s/backend.yaml
  k8s/kustomization.yaml
  k8s/mysql.yaml
  src/main/resources/application-prod.yaml
Labels: feat

#20 서버 설정정보 추가
  k8s/backend.yaml
Labels: feat

#23 jdk 변경
  Dockerfile
Labels: feat

#29 feat. 문제 목록 조회 구현
  http/problem/CreateProblem.http
  src/main/java/clofi/codeython/problem/controller/ProblemController.java
  src/main/java/clofi/codeython/problem/controller/response/AllProblemResponse.java
  src/main/java/clofi/codeython/problem/domain/Record.java
  src/main/java/clofi/codeython/problem/repository/ProblemRepository.java
  src/main/java/clofi/codeython/problem/repository/RecordRepository.java
  src/main/java/clofi/codeython/problem/service/ProblemService.java
  src/test/java/clofi/codeython/problem/service/ProblemServiceTest.java
Labels: feat

#31 feat. 기록조회구현
  src/main/java/clofi/codeython/member/controller/MemberController.java
  src/main/java/clofi/codeython/member/service/MemberService.java
  src/main/java/clofi/codeython/problem/controller/ProblemController.java
  src/main/java/clofi/codeython/problem/controller/response/RecordResponse.java
  src/main/java/clofi/codeython/problem/domain/Record.java
  src/main/java/clofi/codeython/problem/repository/ProblemRepository.java
  src/main/java/clofi/codeython/problem/repository/RecordRepository.java
  src/main/java/clofi/codeython/problem/service/ProblemService.java
  src/test/java/clofi/codeython/problem/service/ProblemServiceTest.java
Labels: feat

#32 feat. 문제 등록 기능 변수 추가 구현
  src/main/java/clofi/codeython/common/util/StringListConverter.java
  src/main/java/clofi/codeython/problem/domain/Hiddencase.java
  src/main/java/clofi/codeython/problem/domain/Language.java
  src/main/java/clofi/codeython/problem/domain/Problem.java
  src/main/java/clofi/codeython/problem/domain/Record.java
  src/main/java/clofi/codeython/problem/domain/Testcase.java
  src/main/java/clofi/codeython/problem/domain/request/CreateProblemRequest.java
  src/main/java/clofi/codeython/problem/domain/request/HiddencaseRequest.java
  src/main/java/clofi/codeython/problem/domain/request/TestcaseRequest.java
  src/main/java/clofi/codeython/problem/repository/HiddencaseRepository.java
  src/main/java/clofi/codeython/problem/repository/LanguageRepository.java
  src/main/java/clofi/codeython/problem/repository/RecordRepository.java
  src/main/java/clofi/codeython/problem/repository/TestcaseRepository.java
  src/main/java/clofi/codeython/problem/service/ProblemService.java
  src/test/java/clofi/codeython/problem/service/ProblemServiceTest.java
Labels: feat

#34 feat. 문제 상세 조회 구현
  src/main/java/clofi/codeython/problem/controller/ProblemController.java
  src/main/java/clofi/codeython/problem/controller/response/BaseCodeResponse.java
  src/main/java/clofi/codeython/problem/controller/response/GetProblemResponse.java
  src/main/java/clofi/codeython/problem/controller/response/TestcaseResponse.java
  src/main/java/clofi/codeython/problem/repository/LanguageRepository.java
  src/main/java/clofi/codeython/problem/repository/ProblemRepository.java
  src/main/java/clofi/codeython/problem/repository/TestcaseRepository.java
  src/main/java/clofi/codeython/problem/service/ProblemService.java
  src/test/java/clofi/codeython/problem/service/ProblemServiceTest.java
Labels: feat

#41 배포 설정 정보 변경
  Dockerfile
  build.gradle
  k8s/backend.yaml
  k8s/mysql.yaml
Labels: feat

#45 경기장관련 Entity 생성
  src/main/java/clofi/codeython/room/domain/Room.java
  src/main/java/clofi/codeython/room/domain/RoomMember.java
Labels: feat

#48 배포 설정 변경
  Dockerfile
Labels: feat

#50 배포 파일 경로 수정
  Dockerfile
Labels: feat

#52 feat. 경기장 생성 기능 구현
  src/main/java/clofi/codeython/room/controller/RoomController.java
  src/main/java/clofi/codeython/room/controller/response/CreateRoomResponse.java
  src/main/java/clofi/codeython/room/domain/Room.java
  src/main/java/clofi/codeython/room/domain/request/CreateRoomRequest.java
  src/main/java/clofi/codeython/room/repository/RoomRepository.java
  src/main/java/clofi/codeython/room/service/RoomService.java
  src/test/java/clofi/codeython/room/service/RoomServiceTest.java
Labels: feat

#51 Feat/#33 비밀번호입장 및 초대코드입장
  src/main/java/clofi/codeython/jwt/JWTFilter.java
  src/main/java/clofi/codeython/room/controller/RoomController.java
  src/main/java/clofi/codeython/room/controller/response/RoomResponse.java
  src/main/java/clofi/codeython/room/domain/RoomMember.java
  src/main/java/clofi/codeython/room/repository/RoomMemberRepository.java
  src/main/java/clofi/codeython/room/repository/RoomRepository.java
  src/main/java/clofi/codeython/room/service/RoomService.java
  src/main/java/clofi/codeython/room/service/request/WaitRoomRequest.java
  src/main/java/clofi/codeython/socket/config/WebSocketConfig.java
  src/main/java/clofi/codeython/socket/controller/SocketController.java
  src/main/java/clofi/codeython/socket/controller/response/SocketUserResponse.java
  src/main/java/clofi/codeython/socket/service/SocketService.java
Labels: feat

#57 d2hub 경로 변경
  k8s/backend.yaml
Labels: feat

#60 feat.소켓 CONNECT, DISCONNECT, SEND 구현
  src/main/java/clofi/codeython/member/repository/MemberRepository.java
  src/main/java/clofi/codeython/room/controller/response/RoomResponse.java
  src/main/java/clofi/codeython/room/repository/RoomMemberRepository.java
  src/main/java/clofi/codeython/socket/config/StompHandler.java
  src/main/java/clofi/codeython/socket/config/WebSocketConfig.java
  src/main/java/clofi/codeython/socket/controller/SocketController.java
  src/main/java/clofi/codeython/socket/controller/response/ChatMessage.java
  src/main/java/clofi/codeython/socket/service/SocketService.java
Labels: feat

#66 문제 목록 조회되지 않는 문제 수정
  src/main/java/clofi/codeython/problem/controller/ProblemController.java
  src/main/java/clofi/codeython/problem/judge/service/JudgeService.java
  src/main/java/clofi/codeython/problem/service/ProblemService.java
  src/test/java/clofi/codeython/problem/service/ProblemServiceTest.java
Labels: bug

#70 feat. 랭킹 조회 기능 구현
  http/member/CreateMember.http
  http/problem/CreateProblem.http
  src/main/java/clofi/codeython/member/controller/MemberController.java
  src/main/java/clofi/codeython/member/controller/response/RankerResponse.java
  src/main/java/clofi/codeython/member/controller/response/RankingResponse.java
  src/main/java/clofi/codeython/member/domain/Member.java
  src/main/java/clofi/codeython/member/repository/MemberRepository.java
  src/main/java/clofi/codeython/member/service/MemberService.java
  src/test/java/clofi/codeython/member/service/MemberServiceTest.java
Labels: feat

#74 웹소켓 데이터 타입 정의
  src/main/java/clofi/codeython/socket/controller/SocketController.java
  src/main/java/clofi/codeython/socket/controller/response/DataResponse.java
  src/main/java/clofi/codeython/socket/controller/response/DataType.java
Labels: enhancement

#79 공개 경기장 생성시 예외 발생 해결
  src/main/java/clofi/codeython/room/domain/Room.java
  src/main/java/clofi/codeython/room/service/RoomService.java
Labels: feat

#78 feat. 랭킹 조회시 레벨 항목 추가
  src/main/java/clofi/codeython/member/controller/response/RankerResponse.java
  src/main/java/clofi/codeython/member/service/MemberService.java
  src/main/java/clofi/codeython/socket/service/SocketService.java
Labels: feat

#83 feat. 방 입장, 퇴장시 방장 정보 전송 추가
  src/main/java/clofi/codeython/room/service/RoomService.java
  src/main/java/clofi/codeython/socket/controller/response/SocketUserResponse.java
  src/main/java/clofi/codeython/socket/service/SocketService.java
Labels: feat

#96 부호를 포함한 3자리 패스워드가 통과되는 문제 수정
  src/main/java/clofi/codeython/room/domain/Room.java
  src/main/java/clofi/codeython/room/service/RoomService.java
  src/test/java/clofi/codeython/room/service/RoomServiceTest.java
Labels: bug

#92 정답 코드를 제출할 때마다 경험치가 올라가는 문제 수정, 등수 로직 수정, 혼자 게임을 시작할 수 있는 문제 수정
  src/main/java/clofi/codeython/member/domain/Member.java
  src/main/java/clofi/codeython/problem/judge/service/JudgeService.java
  src/main/java/clofi/codeython/room/domain/Room.java
  src/main/java/clofi/codeython/room/domain/RoomMember.java
  src/main/java/clofi/codeython/room/service/RoomService.java
Labels: bug

#94 사용자 경험치 통째로 가는 문제 수정
  src/main/java/clofi/codeython/member/service/MemberService.java
Labels: bug

#99 username 중복 생성 문제 수정
  src/main/java/clofi/codeython/member/domain/Member.java
  src/main/java/clofi/codeython/problem/core/domain/Problem.java
  src/main/java/clofi/codeython/room/domain/Room.java
  src/test/java/clofi/codeython/room/service/RoomServiceTest.java
Labels: bug

#101 같이놀기 기록 조회가 되지 않는 문제 수정
  src/main/java/clofi/codeython/problem/core/domain/Record.java
  src/main/java/clofi/codeython/problem/core/repository/RecordRepository.java
  src/main/java/clofi/codeython/problem/core/service/ProblemService.java
  src/main/java/clofi/codeython/problem/judge/service/JudgeService.java
Labels: bug

#106 자바스크립트 스트링 출력 시 문제 채점이 제대로 되지 않는 문제 수정
  src/main/java/clofi/codeython/problem/judge/domain/creator/JavascriptExecutionFileCreator.java
Labels: bug

#103 모든 테스트 케이스가 클라이언트한테 반환되는 문제 수정
  src/main/java/clofi/codeython/problem/core/service/ProblemService.java
  src/main/java/clofi/codeython/problem/judge/domain/ResultCalculator.java
Labels: bug

#108 RoomMember가 DB에 남아있어서 사용자가 어떤 방도 들어가지 못하는 문제 수정
  src/main/java/clofi/codeython/room/domain/RoomMember.java
  src/main/java/clofi/codeython/room/service/RoomService.java
Labels: bug
